language: c
install:
    - autoreconf --install
    - ./configure --prefix="$BASHLIB_PREFIX"
    - make
    - make install
env:
    - BASHLIB_PREFIX=/tmp/bashlib PATH="$BASHLIB_PREFIX/bin:$PATH"
before_script:
    - git clone https://github.com/sstephenson/bats.git
    - PREFIX="$BASHLIB_PREFIX" ./bats/install.sh
script:
    - bats --tap test
notifications:
    email:
        on_success: never
